"""Render a validated StarterKit as the README the user receives. Code only."""

from __future__ import annotations

import re

from app.schemas import StarterKit

_PIPE = re.compile(r"\|")


def _cell(text: str, limit: int = 160) -> str:
    """Safe Markdown table cell: no pipes or newlines, bounded length."""
    text = _PIPE.sub("/", " ".join(str(text).split()))
    return text if len(text) <= limit else text[: limit - 1] + "…"


def _rows(n: int | None) -> str:
    if n is None:
        return "?"
    return f"{n / 1e6:.1f}M" if n >= 1e6 else f"{n / 1e3:.1f}k" if n >= 1e3 else str(n)


def quick_start(kit: StarterKit, hf_task: str) -> str | None:
    """A copy-paste snippet using only verified ids and trust_remote_code=False."""
    if not kit.models:
        return None
    model = kit.models[0].repo_id
    lines = [
        "from transformers import pipeline",
        "",
        f'pipe = pipeline("{hf_task}", model="{model}", trust_remote_code=False)',
    ]
    if kit.datasets:
        ds = kit.datasets[0]
        split = ds.splits[0] if ds.splits else "train"
        config = f', "{ds.config}"' if ds.config else ""
        lines = [
            "from datasets import load_dataset",
            *lines,
            f'data = load_dataset("{ds.repo_id}"{config}, split="{split}", streaming=True)',
            "sample = next(iter(data))",
            "print(sample)",
        ]
    return "\n".join(lines)


def render_readme(kit: StarterKit) -> str:
    c = kit.constraints
    hardware = "CPU only" if c.cpu_only else f"{c.gpu_vram_gb:g} GB GPU"
    licence = "commercial use" if c.commercial_use else "non-commercial use"
    langs = ", ".join(c.languages) if c.languages else "any language"
    date = kit.created_at.strftime("%Y-%m-%d")
    out: list[str] = [
        f"# Starter kit: {c.task_description}",
        "",
        f"> Generated by HubScout on {date} · {licence} · {hardware} · {langs}",
        f"> {len(kit.links)} links, each verified to exist on {date}"
        f" ({kit.sources_checked} candidates checked).",
        "",
        "## TL;DR",
        "",
        kit.tldr,
        "",
    ]

    out += ["## 1. Models", ""]
    if kit.models:
        out += [
            "| # | Model | Why | Licence | Size / fit | Updated |",
            "|---|---|---|---|---|---|",
        ]
        for i, m in enumerate(kit.models, 1):
            fit = f"{m.params_billion:g} B · ~{m.est_vram_gb} GB {m.precision}"
            updated = m.last_modified.strftime("%Y-%m") if m.last_modified else "?"
            why = m.reasons[0] if m.reasons else ""
            out.append(
                f"| {i} | [{m.repo_id}]({m.url}) | {_cell(why)} | {m.licence} | {fit} | {updated} |"
            )
        notes = [f"- **{m.repo_id}**: {n}" for m in kit.models for n in m.notes]
        out += ["", *notes] if notes else []
    else:
        out.append("_No model passed verification (see gaps below)._")
    out.append("")

    out += ["## 2. Datasets", ""]
    if kit.datasets:
        out += [
            "| # | Dataset | Why | Licence | Rows / splits | Linked to |",
            "|---|---|---|---|---|---|",
        ]
        for i, d in enumerate(kit.datasets, 1):
            linked = f"used to train {', '.join(d.used_by)}" if d.used_by else "—"
            splits = "/".join(d.splits[:4]) or "?"
            out.append(
                f"| {i} | [{d.repo_id}]({d.url}) | {_cell(d.why)} | {d.licence} | "
                f"{_rows(d.num_rows)} · {splits} | {_cell(linked, 80)} |"
            )
        for d in kit.datasets:
            if d.sample_rows:
                cols = list(d.sample_rows[0])[:4]
                out += [
                    "",
                    f"<details><summary>Sample rows: {d.repo_id}</summary>",
                    "",
                    "| " + " | ".join(cols) + " |",
                    "|" + "---|" * len(cols),
                    *(
                        "| " + " | ".join(_cell(row.get(col, ""), 80) for col in cols) + " |"
                        for row in d.sample_rows
                    ),
                    "",
                    "</details>",
                ]
    else:
        out.append("_No dataset passed verification (see gaps below)._")
    out.append("")

    out += ["## 3. Methods and approaches", ""]
    if kit.methods:
        out += ["| # | Resource | Type | Why | Linked to |", "|---|---|---|---|---|"]
        for i, r in enumerate(kit.methods, 1):
            kind = f"{r.kind} ({r.published[:4]})" if r.published else r.kind
            linked = f"describes {', '.join(r.describes)}" if r.describes else "—"
            out.append(
                f"| {i} | [{_cell(r.title, 90)}]({r.url}) | {kind} | {_cell(r.why)} | "
                f"{_cell(linked, 80)} |"
            )
    else:
        out.append("_No method resource passed verification (see gaps below)._")
    out.append("")

    out += ["## How these fit together", "", kit.fit_story, ""]

    if kit.quick_start:
        out += ["## Quick start", "", "```python", kit.quick_start, "```", ""]

    if kit.rejected:
        out += [f"## What we ruled out ({len(kit.rejected)})", ""]
        out += [
            f"- `{r.repo_id}` ({r.kind}): {_cell('; '.join(r.reasons), 200)}"
            for r in kit.rejected[:12]
        ]
        if len(kit.rejected) > 12:
            out.append(f"- …and {len(kit.rejected) - 12} more")
        out.append("")

    if kit.gaps or kit.assumptions:
        out += ["## Gaps and assumptions", ""]
        out += [f"- {g}" for g in kit.gaps] + [f"- Assumed: {a}" for a in kit.assumptions]
        out.append("")

    out += [
        "## Run details",
        "",
        f"LLMs used: {', '.join(kit.models_used) or 'none'} · candidates checked: "
        f"{kit.sources_checked} · generated {kit.created_at.isoformat(timespec='seconds')}",
        "",
    ]
    return "\n".join(out)
