#!/usr/bin/env bash
# Create the two local env files if they do not exist yet. Never overwrites, never
# prints secret values.
#   .env        your external API keys (copied empty from .env.example; you fill it in)
#   .env.infra  generated local infrastructure secrets (Postgres, SearXNG, Langfuse, API)
set -euo pipefail
cd "$(dirname "$0")/.."
umask 077

if [[ -e .env ]]; then
  echo ".env exists; left unchanged."
else
  cp .env.example .env
  echo "Created .env from .env.example; paste your API keys into it."
fi

if [[ -e .env.infra ]]; then
  echo ".env.infra exists; left unchanged."
  exit 0
fi

hex() { openssl rand -hex "$1"; }
lf_pk="pk-lf-$(hex 16)"
lf_sk="sk-lf-$(hex 16)"

cat > .env.infra <<INFRA
# Generated by scripts/init_env.sh on $(date -I). Local development secrets only.
# Do not edit or commit. Delete this file and re-run the script to rotate
# (existing Docker volumes keep the old Postgres/Langfuse passwords).
POSTGRES_PASSWORD=$(hex 24)
SEARXNG_SECRET=$(hex 32)
API_AUTH_KEY=$(hex 32)
LANGFUSE_NEXTAUTH_SECRET=$(hex 32)
LANGFUSE_SALT=$(hex 16)
LANGFUSE_ENCRYPTION_KEY=$(hex 32)
LANGFUSE_DB_PASSWORD=$(hex 24)
LANGFUSE_CLICKHOUSE_PASSWORD=$(hex 24)
LANGFUSE_MINIO_PASSWORD=$(hex 24)
LANGFUSE_REDIS_PASSWORD=$(hex 24)
LANGFUSE_INIT_USER_PASSWORD=$(hex 12)
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=$lf_pk
LANGFUSE_INIT_PROJECT_SECRET_KEY=$lf_sk
LANGFUSE_PUBLIC_KEY=$lf_pk
LANGFUSE_SECRET_KEY=$lf_sk
INFRA
echo "Created .env.infra with generated local secrets (mode 600)."
